# Generated by Django 4.2 on 2023-05-04 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_alter_tradingbot_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='tradingbot',
            name='date_time',
            field=models.DateTimeField(null=True),
        ),
    ]
