# Generated by Django 4.2 on 2023-05-05 00:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0004_alter_tradingbot_date_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tradingbot',
            name='date_time',
        ),
    ]
